// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-streams.ts
import { createClient } from "npm:@supabase/supabase-js@^2.56.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_streams_default = defineTool({
  name: "list_streams",
  title: "List streams",
  description: "List the signed-in user's Hyvo streams (live and past).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return (default 20)."),
    only_live: z.boolean().optional().describe("If true, only currently live streams.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, only_live }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb(ctx).from("streams").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (only_live) q = q.eq("is_live", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { streams: data }
    };
  }
});

// src/lib/mcp/tools/get-analytics.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.56.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_analytics_default = defineTool2({
  name: "get_stream_analytics",
  title: "Get stream analytics",
  description: "Fetch recent analytics snapshots (viewer counts, chat rate, etc.) for the signed-in user's streams.",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).optional().describe("Max snapshots (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb2(ctx).from("stream_analytics").select("*").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { snapshots: data }
    };
  }
});

// src/lib/mcp/tools/schedule-stream.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.56.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var schedule_stream_default = defineTool3({
  name: "schedule_stream",
  title: "Schedule a stream",
  description: "Create a scheduled stream on the user's Hyvo calendar.",
  inputSchema: {
    title: z3.string().trim().min(1).describe("Stream title."),
    platform: z3.string().describe("Platform slug, e.g. 'twitch' or 'youtube'."),
    scheduled_start_time: z3.string().describe("ISO 8601 datetime for when the stream starts."),
    duration: z3.number().int().min(1).optional().describe("Planned duration in minutes."),
    description: z3.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async ({ title, platform, scheduled_start_time, duration, description }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb3(ctx).from("stream_schedules").insert({
      user_id: ctx.getUserId(),
      title,
      platform,
      scheduled_start_time,
      duration: duration ?? 60,
      description: description ?? null,
      status: "scheduled"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Scheduled: ${data.title} on ${data.platform} @ ${data.scheduled_start_time}` }],
      structuredContent: { schedule: data }
    };
  }
});

// src/lib/mcp/tools/list-schedule.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.56.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_schedule_default = defineTool4({
  name: "list_scheduled_streams",
  title: "List scheduled streams",
  description: "List the signed-in user's upcoming scheduled streams.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb4(ctx).from("stream_schedules").select("*").eq("user_id", ctx.getUserId()).order("scheduled_start_time", { ascending: true }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { schedules: data }
    };
  }
});

// src/lib/mcp/tools/generate-title.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
var generate_title_default = defineTool5({
  name: "generate_stream_title",
  title: "Generate stream titles",
  description: "Generate catchy, click-worthy stream title ideas for a given game and vibe using Hyvo AI.",
  inputSchema: {
    game: z5.string().describe("Game or content category, e.g. 'Valorant'."),
    mood: z5.string().optional().describe("Vibe/mood, e.g. 'hype', 'chill', 'chaotic'."),
    count: z5.number().int().min(1).max(10).optional().describe("How many titles (default 5).")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ game, mood, count }, ctx) => {
    const key = process.env.LOVABLE_API_KEY;
    if (!key) return { content: [{ type: "text", text: "LOVABLE_API_KEY not configured" }], isError: true };
    const n = count ?? 5;
    const res = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", "Lovable-API-Key": key },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [
          { role: "system", content: "You generate short, punchy Twitch/YouTube live stream titles. Return one per line, no numbering." },
          { role: "user", content: `Game/topic: ${game}
Mood: ${mood ?? "hype"}
Generate ${n} titles.` }
        ]
      })
    });
    if (!res.ok) return { content: [{ type: "text", text: `AI gateway error: ${res.status}` }], isError: true };
    const data = await res.json();
    const text = data?.choices?.[0]?.message?.content ?? "";
    const titles = text.split("\n").map((s) => s.trim()).filter(Boolean).slice(0, n);
    return {
      content: [{ type: "text", text: titles.join("\n") }],
      structuredContent: { titles }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fxvvcyjwgxxxezqzucwm";
var mcp_default = defineMcp({
  name: "hyvo-mcp",
  title: "Hyvo.ai Streaming Assistant",
  version: "0.1.0",
  instructions: "Tools for Hyvo.ai \u2014 the AI-powered live streaming assistant. Use these to list a streamer's streams, view analytics, manage their schedule, and generate stream titles.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_streams_default, get_analytics_default, schedule_stream_default, list_schedule_default, generate_title_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
