// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxvvcyjwgxxxezqzucwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4dnZjeWp3Z3h4eGV6cXp1Y3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MzExNzEsImV4cCI6MjA3MTEwNzE3MX0.Lv6PT9SfKcNWHmnFHi3Nr7RiPVwe-vurSN3u-82yCg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});